steps:
# Install dependencies
- name: 'python:3.9'
  entrypoint: pip
  args: ['install', '-r', 'requirements.txt', '--user']

# Decrypt secrets if needed (optional)
# - name: 'gcr.io/cloud-builders/gcloud'
#   args:
#   - kms
#   - decrypt
#   - --ciphertext-file=encrypted-credentials.json.enc
#   - --plaintext-file=credentials.json
#   - --location=global
#   - --keyring=my-keyring
#   - --key=my-key

# Set up environment
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "ANTHROPIC_API_KEY=$$ANTHROPIC_API_KEY" > .env
      echo "GOOGLE_APPLICATION_CREDENTIALS=$$GOOGLE_APPLICATION_CREDENTIALS" >> .env
  secretEnv: ['ANTHROPIC_API_KEY', 'GOOGLE_APPLICATION_CREDENTIALS']

# Deploy to App Engine
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud app deploy --quiet']

timeout: '1600s'

# Define your secrets here
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/anthropic-api-key/versions/latest
      env: 'ANTHROPIC_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/firebase-credentials/versions/latest
      env: 'GOOGLE_APPLICATION_CREDENTIALS'