steps:
# Install dependencies
- name: 'python:3.9'
  entrypoint: pip
  args: ['install', '-r', 'requirements.txt']

# Install Node.js dependencies
- name: 'node:16'
  entrypoint: npm
  args: ['install']

# Build frontend assets
- name: 'node:16'
  entrypoint: npm
  args: ['run', 'build']

# Setup environment
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "ANTHROPIC_API_KEY=$$ANTHROPIC_API_KEY" > .env
      echo "GOOGLE_APPLICATION_CREDENTIALS=$$GOOGLE_APPLICATION_CREDENTIALS" >> .env
  secretEnv: ['ANTHROPIC_API_KEY', 'GOOGLE_APPLICATION_CREDENTIALS']

# Deploy to App Engine
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud app deploy --quiet']

timeout: '1600s'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/anthropic-api-key/versions/latest
      env: 'ANTHROPIC_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/firebase-credentials/versions/latest
      env: 'GOOGLE_APPLICATION_CREDENTIALS'